### ISSUE TITLE
Include link to Issue template in Submission Form First Page

### ISSUE THREAD

**Issue by nathanfletcher** [dpgabot/submission-digitalpublicgoods#95]
### Issue description

In efforts to make bug and ticket reporting smoother for potential nominees using the form, it would be great to have a button or link that exists on the form to send non-GitHub savvy users directly to GitHub.
Currently, on the first page of the form, only the support email is provided

### What's the expected result?
Click a link or button during the application process to report any issues

### What's the actual result?
There is a support email on the first page that 

### Additional details

- What browser did this occur on?
 - Non-specific issue on browsers

**Comment by amreenp7** [comment]
Email is suffice for now. Options could include: templated email embedded on the page or a form that users can fill out.
