### ISSUE TITLE
[BUG] Incorrectly encoded Repositories key in Nominee JSON

### ISSUE THREAD

**Issue by nathanbaleeta** [dpgabot/submission-digitalpublicgoods#99]
![Screenshot from 2022-01-20 11-08-18](https://user-images.githubusercontent.com/8824104/150694589-b8cdbd46-41ee-4aaf-9954-4052a2e2b25b.png)

@nathanfletcher @lacabra  In an attempt to resolve the CI failing on https://github.com/DPGAlliance/publicgoods-candidates/pull/936, I got the above error which shows the `repositories` payload is not generated correctly i.e. it duplicates the `repositories key`. The new culprit seems to be [here](https://github.com/dpgabot/submission-digitalpublicgoods/blob/main/schemas/schema.js#L130), but suprisingly the form renders perfectly. The above bug has been propagated to recently created PR [Aajeevika](https://github.com/DPGAlliance/publicgoods-candidates/pull/937)

- A couple of trial and error attempts show that using this convention (`name` & `url`) for naming variables versus `repositories.name` & `repositories.url` yields correct JSON structure.

**PS:** This issue continues the discussion that started on #98

**Comment by nathanfletcher** [comment]
I'm wondering if it may be because the schema that tests the nominee JSON still has the `repositoryURL` key and still checks for it. Initial thoughts.

**Comment by lacabra** [comment]
Fixed through #101
